apiVersion: v1
kind: Service
metadata:
  name: nebula-vault-service
spec:
  type: NodePort
  selector:
    app: nebula-vault
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
